### ISSUE TITLE
~suggest for IRC bot

### ISSUE THREAD

**Issue by balohmatevz** [OneHourGameJam/OneHourGameJam#11]
Could use a ~suggest command for the IRC bot which prints out "Unfortunately I can't remember every suggestion made on IRC. Please take a moment and write down your suggestion here: https://github.com/OneHourGameJam/OneHourGameJam/issues/new Thanks!"

**Comment by WetDesertRock** [comment]
I would, however not sure how useful it would be. Because it is a verb, it suggests that the command would be to suggest something. However since it is a help topic, I think I might suggest another route. A ~help, or ~topic command that has a second command for whatever it spits out. This would be merged with the current ~explain. 

IE:
```
WetDesertRock: ~topic Feature
ohgj: If you have a suggestion for the jam, please write down your suggestion here: https://github.com/OneHourGameJam/OneHourGameJam/issues/new
```

A possible expansion would be the ability for ops/admins to add new topics:
```
LimeLiam: ~addtopic Feature If you have a suggestion for the jam, please write down your suggestion here: https://github.com/OneHourGameJam/OneHourGameJam/issues/new
ohgj: Topic added
```
In which it could be accessed later by another `~topic Feature` command.

**Comment by WetDesertRock** [comment]
Also why I prefer `~topic` over `~help` is the fact that help may be related to how to use the bot. Rather than how to do the jam.

**Comment by balohmatevz** [comment]
I don't have a preference as to the word used, I just need it to work like ~explain, so I can use it when people write bug reports and / or enhancement requests on IRC.

**Comment by WetDesertRock** [comment]
Added in:
```
~topic <title> [target]
~topicedit <title> <message>
~topicappend <title> <message>
~topicremove <title>
~topiclist
```

`~topicedit` is how you make a new topic, and it overwrites any existing topic. If you want the bot to send multiple messages, use `~topicappend`. The rest is self explanatory.

This is where I'd close the issue, but don't have the powers to.

**Comment by balohmatevz** [comment]
:+1:
