### ISSUE TITLE
Use bcrypt

### ISSUE THREAD

**Issue by pta2002** [OneHourGameJam/OneHourGameJam#58]
SHA isn't meant for password hashing these days, and while the current way isn't necessarily insecure, bcrypt would surely be better. Suggestion: use PHP's password functions

**Comment by balohmatevz** [comment]
Doing this would require a password hasing versioning system. Since there is no good way to unhash existing passwords (that's sort of the point of this), it'd be impossible to rehash them using the new hasing system until a user enters their password again. the passwords, hashed with SHA256 between 10k and 20k times could be further hashed with bcrypt, which would result in even more CPU power being necessary to validate entered passwords. The reason bcrypt isn't used is to support PHP 5.4, which doesn't have the functionality. And honestly I think hasing a salted and peppered password between 10k and 20k times is way beyond the requirements for a site like this. 

That said, if you want to make a hashing versioning system, go ahead.  😄

**Comment by vintprox** [comment]
> that's sort of the point of this

Hmmmm... ok.

**Comment by liambaloh** [comment]
The authentication versioning system was split out into task #138 which is a pre-requisite for this task
