### ISSUE TITLE
Cutting edge experience with AJAX/sockets

### ISSUE THREAD

**Issue by vintprox** [OneHourGameJam/OneHourGameJam#87]
I would call using WebSockets or Socket.io just a necessary feature of the website like 1HGJ, and all because of:

- games list staying still,
- lack of live stream announcement (#86).

Everything is awaiting PHP to process on page refresh, but that doesn't have to go this way.

I foresee the potential behind One Hour Game Jam website, so I would gladly help with refactoring. Also, it should be clear how current hardware (VDS/VPS/Shared) is capable of running socket server (or any)?

---

UPD.
OK, sockets are not panacea all along. We can make it oldschool style via AJAX calls to PHP REST API!

---

P. S.: Yes, server-side rendering should also be implemented along with all initial requests.

**Comment by vintprox** [comment]
Ok, so the website is on shared hosting, but someone also has bots running, which is good environment for Socket.io server, live API of the website.

AFAIK you can connect to socket.io cross domain, so integration is possible. BTW double-check is needed here.

**Comment by mkalam-alami** [comment]
That's an interesting idea. Though that would mean indeed that a separate NodeJS webserver has to be hosted, interacting with the actual website by polling a secure API.

If the shared hosting service allows it, it's important to configure the proxy so that Socket.io is served from the same domain name as the main site. Otherwise that means cross-domain requests will have to fall back to JSONP polling... And if we use JSONP polling, Socket.io becomes not any better than directly polling the PHP API with jQuery! At least I think it would not be worth the trouble.

**Comment by liambaloh** [comment]
If we were to do this, it'd require a major re-architecting of the site, shifting focus from php to javascript, and from files in the php folder to those in the api folder, including many new ones. 

To be clear, I'm not against this, but it's so far down the line that I just don't think it's overly realistic for right now, and I'm hesitant to keep long-term architecture design tickets open, as they tend to be vague and don't really have a clear completion state.

Also please not AJAX, please use JSON.

**Comment by mkalam-alami** [comment]
Doesn't the X in AJAX already mean JSON? ;)
