### ISSUE TITLE
[Unassigned!] Revalidating design

### ISSUE THREAD

**Issue by vintprox** [OneHourGameJam/OneHourGameJam#89]
Hello there! I feel it's more like opportunity to know you folks better after filling this survey. There are key points THAT GUY personally would like to know about the audience thinking of design for jam route, and you can familiarize ourselves with your point of view of **OneHourGameJam website** right here!

1. So, what do you think about the whole **color scheme**?
2. What **pain points** did you encounter while browsing OneHourGameJam website?
3. If there was some **announcement about a stream**, how do you expect to recognize it? See also: #86. You wanna see it:
    
    - at the **bottom** of view,
    - at the **top** of view **within menu**,
    - at the top of view, but **under the menu**,
    - **preview** of current jam **at the side**,
    - preview of current jam **stretched to full page** horizontally,
    - small **video** at the side,
    - video stretched to full page horizontally **(brutal, huh?)**.
    
4. Do you really like **side bar** or you'd prefer to see **top menu only**?
5. Would you like **full-page overview** of each game or to stay **flipping cards**? Or maybe flipping cards transition to full-page?
6. Will you understand that **night mode** could be activated by openning little User Settings menu followed by **cog icon** as soon as possible?
7. Are you annoyed by instantly animated **GIF previews**?
8. Do you want to see website with **just not** white background?
9. Maybe **larger font**?
10. How would you react on **Twitter feed** placed on main page?
11. Would you like to know how many users on Discord server are **online** via website?

##### Thank you for your precious time.

Leaving this task for somebody else here, because I'm up to primary job projects.

**Comment by mkalam-alami** [comment]
1. Currently the color scheme is quite plain, close to a default Bootstrap app. So if there's a rebranding to do I wouldn't mind trying to stay in line with what exists. I like the pixel art of the logo so maybe it could serve as a reference maybe? Like either light or dark background, with highlights of pinks and purples, and pixel-arty fonts for titles?

2. No particular issues with navigation, except maybe performance (pages can be slow to load). IIRC there's a lot of room for improving performance in the code.

3. A large banner under the main header, like last time I saw it is fine. I think it loads a full embed? I don't mind this way.

4. Top bars can be more of a headache to fit things propertly (dynamic menus & stuff), so since the current navigation works fine I don't feel it worth reorganizing stuff.

5. I don't think it's worth having full page for games. Otherwise it will be an incentive for filling long descriptions with instructions and all. Here it's all compact and nice, not unlike what made Twitter a success.

6. Night mode from User Settings is ok. But why not add a toggle in a page corner.

7. Not annoyed by instantly animated GIF previews. 1HGJ games are ugly and I like them.

8. White background is not horrible, but why not rework the theme (see 1)

9. I don't mind the current font size, it allows to list plenty of games in a compact way.

10. Twitter feed is currently just regaular jam reminders and a couple guys sharing their game on #1hgj, so nothing worth integrating to the front page I think.

11. If knowing how many Discord users are online can help people joining the server, why not
