### ISSUE TITLE
Logged in to other person's account after signing up

### ISSUE THREAD

**Issue by vintprox** [OneHourGameJam/OneHourGameJam#98]
Well, I was registering under name `vintprox`, then I got weird welcoming: `Hello pr0te`!

![screenshot_2019-01-06-22-13-43](https://user-images.githubusercontent.com/5708819/50740611-fe2add00-1201-11e9-8c06-781e3b885b05.png)

Turns out it's the account registered right before my own. After logging out and in to my account the bug is not encountered.

And this bug leads to some new user accessing my account.

**Comment by balohmatevz** [comment]
There appears to have been a data migration error, where a user's username was migrated as blank back in 2016. The recent refactor from 76281ad79dfc12af73c89ba4aa1175b22c886d71 seems to have exposed this data problem. At the moment it looks like this bug is isolated to the deployed site on https://onehourgamejam.com but I'll take a closer look and update this thread.

Initial observations indicate there is data visibility but no ability to edit another user's data. Since the vast majority of data is public anyway, most of the site can continue to operate despite this. I have however temporarily disabled access to the two sections, which hold private data: The User Data page and the User Settings page.

**Comment by balohmatevz** [comment]
Turns out there was an issue with the registration code, where registering failed to log in the user properly, logging them in with a session user id 0. When checked against the users, this resulted with nothing, which was interpreted as username "". In the deployed site a migration data error resulted in a real user having the username "", meaning newly registered users had access to their data. The user was notified immediately.

**Comment by vintprox** [comment]
Probably it's the notice to be cautious about any variables that can somehow assign to any zero values. Hopefully you tracked it in timely manner :)
